POST http://localhost:8000/Interface/Initiate/CustomerOnboarding
Content-Type: application/json

{
  "email": "t2est@email.com",
  "password": "12345678",
  "first_name": "Test",
  "last_name": "Customer",
  "phone_number": "1234567890"
}

###
POST http://localhost:8000/api/v1/auth/initiate/customer-signup
Content-Type: application/json

{
  "email": "Fire rules"
}

###
